import type { Metadata } from "next";
import { Geist, Geist_Mono, Cairo } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/Sidebar";
import Navbar from "./components/navbar/Navbar";
import SidebarProvider from "../app/components/context/SidebarContext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cairo = Cairo({
  // variable: "--font-cairo",
  weight: ['500', '600', '700'],

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tahwul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.className} antialiased font-cairo`}
      >
        <SidebarProvider>
          <div className="flex">
            <Sidebar />
            <div className="w-full">
              <Navbar />
              {children}
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
